test-runner: fix an uninitialized-memory error
Clippy is failing with this error `memory_map`:

    error: calling `set_len()` immediately after reserving a buffer creates uninitialized values

Since the code here is just test code where performance isn't a concern,
fully initialize the vec with zeros and drop the unsafe code.